# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - plasticdetectionreva

on:
  push:
    branches:
      - azure_d
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testsarthakregis.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9a42d8912f994fb6aa8909b6ab8e4d9e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9d3b383baee941199c56d3ceb0f82e74 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testsarthakregis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9a42d8912f994fb6aa8909b6ab8e4d9e }}/testsarthakregis/revaapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'plasticdetectionreva'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bb92f574482b4bd99016bc8d9ae59586 }}
        images: 'testsarthakregis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9a42d8912f994fb6aa8909b6ab8e4d9e }}/testsarthakregis/revaapp:${{ github.sha }}'